version: "3.9"
services:

  test-ubuntu:
    image: "rev9en/sandbox"
    volumes: [./:/opt/myenv]
    environment: [REPO_BRANCH=develop]
    working_dir: /opt/myenv
    command:
      - /bin/sh
      - -c
      - |
        ./install.sh --noninteractive && ./tests/test-installation.sh

  shell:
    image: "rev9en/sandbox"
    volumes: [./:/opt/myenv]
    environment:
      - REPO_BRANCH=develop
      - TELEGRAM_TOKEN
      - TELEGRAM_CHAT_ID
    working_dir: /opt/myenv
    command: /bin/bash

  test-debian:
    image: "bitnami/git"
    volumes: [./:/opt/myenv]
    command: /opt/myenv/install.sh --noninteractive && ./tests/test-installation.sh

  test-alpine:
    image: "alpine"
    volumes: [./:/opt/myenv]
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache git bash
        /opt/myenv/install.sh --noninteractive && ./tests/test-installation.sh
