version: "3.9"
services:

  test-ubuntu:
    image: "rev9en/sandbox"
    volumes: [./:/opt/myenv]
    environment: [REPO_BRANCH=develop]
    command:
      - /bin/sh
      - -c
      - |
        echo "Install myenf first"
        /opt/myenv/install.sh --noninteractive
        echo "Start tests after installation"
        bash


  test-debian:
    image: "bitnami/git"
    volumes: [./:/opt/myenv]
    command: /opt/myenv/install.sh --noninteractive

  test-alpine:
    image: "alpine"
    volumes: [./:/opt/myenv]
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache git bash
        /opt/myenv/install.sh --noninteractive
