select = ["ALL"]

line-length = 120
target-version = "py39"

ignore = [
    "D", "EM", "G", "FBT", "PGH", "TD", "FIX", 
    "ANN002",
    "ANN003",
    "ANN101",
    "ANN204",
    "TRY003",
    "UP007",
]

# File specific settings
# Ignore: E401 - imported but unused
per-file-ignores = {"__init__.py" = ["F401"]}

flake8-quotes = {docstring-quotes = "double", inline-quotes = "double", multiline-quotes = "double"}
