#!/bin/sh
if grep "^ID=" /etc/os-release 2>&1 | grep -q -v openwrt; then echo "OpenWrt is required"; exit 1; fi

echo "---- Router ----"
printf "uptime..: "; uptime | cut -d"," -f1 | sed 's/^[ ]*//g'
printf "memory..: "; echo "$(grep "MemFree" /proc/meminfo | awk '{print $2" "$3}') of $(grep "MemTotal" /proc/meminfo | awk '{print $2" "$3}') free"
printf "address.: "; curl -sL https://checkip.amazonaws.com 2>&1 || true
printf "........: "; ip addr show dev br-lan | grep inet | awk '{print $2}' | cut -d'/' -f1
printf "time....: "; date +%FT%T
printf "opendns : "; ./opendns-check 2>&1 >/dev/null && echo "OK" || "ERROR"
echo "--- clients ----"
show-clients-safe 2>/dev/null || show-clients

