#!/usr/bin/env bash
show_platform() {
    uname -m | sed 's/x86_/x/g' | sed 's/amd/x/g'
}
show_system() {
    if [ "$(uname -s)" == "Darwin" ]; then
        sw_vers | grep Product | cut -d":" -f2 | xargs
        return 0
    fi
    if [ -f "/etc/os-release" ]; then
        name=$(grep "^NAME\|VERSION_ID" /etc/os-release | sort |  sed 's/NAME=//g' | sed 's/VERSION_ID=//g' | sed 's/"//g' | xargs)
        if grep "Microsoft\|WSL" /proc/sys/kernel/osrelease > /dev/null; then
            echo "${name} [WSL]"
        else
            echo "${name}"
        fi
        return 0
    fi
    uname -sr
}
show_uptime() {
    uptime | cut -d"l" -f1 | sed 's/[, ]*$//g' | sed 's/^ //g'
}
show_users() {
    if [ -f "/etc/os-release" ]; then
        if grep "Microsoft\|WSL" /proc/sys/kernel/osrelease > /dev/null; then
            wslvar USERNAME
            return
        fi
    fi
    w -h | cut -d " " -f1 | sort -r | uniq -c | awk '{printf"%s%s (%d)",c,$2,$1;c=", "}'
}
show_ips() {
    if which ifconfig 2>&1 >/dev/null; then
        ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'
    else
        ip add show | grep "inet " | grep -v "127.0.0.1" | sed 's/\// /g' | awk '{print $2}' | sort | xargs | sed -e 's/ /, /g'
    fi
}
# ------[ Customer welcome screen ]--------------------------------------------
if which figlet > /dev/null; then
    echo -en "\033[34m\033[1m"
    hostname | figlet
    echo -en "\033[0m"
else
    echo -e "\033[97m\033[1m  Hostname:\033[0m\033[34m $(hostname)\033[0m"
fi
echo -e "\033[97m\033[1m    System:\033[0m\033[32m $(show_system) ($(show_platform))\033[0m"
echo -e "\033[97m\033[1m     Users:\033[0m\033[93m $(show_users)\033[0m"
echo -e "\033[97m\033[1m Addresses:\033[0m\033[96m $(show_ips | xargs)\033[0m"
echo -e "\033[97m\033[1m    Uptime:\033[0m\033[37m $(show_uptime)\033[0m"
#echo -e "\033[37m══════════════════════════════════════════════════\033[0m"

