#!/bin/sh
read -n 1 -p "Delete XCode Devices and Platforms (y/N)? " opt
echo ""
if [ "${opt}" != "Y" ] && [ "${opt}" != "y" ]; then
    echo "Skip"
else
    echo "Deleting Device Simulators..."
    du -hd 0 $HOME/Library/Developer/CoreSimulator/
    find $HOME/Library/Developer/CoreSimulator/Devices/ -type d -depth 1 | while read f; do rm -r "$f" && echo "Deleted: $f"; done
    du -hd 0 $HOME/Library/Developer/CoreSimulator/
    echo "Delete Device Simulators: Done"

    echo "Deleting XCode Device Platforms..."
    du -hd 0 /Applications/Xcode.app/Contents/Developer/
    echo '  - Deleting: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTV* '
    sudo rm -r /Applications/Xcode.app/Contents/Developer/Platforms/AppleTV* && echo "  - Done"
    echo '  - Deleting: /Applications/Xcode.app/Contents/Developer/Platforms/Watch* '
    sudo rm -r /Applications/Xcode.app/Contents/Developer/Platforms/Watch* && echo "  - Done"
    echo '  - Deleting: /Applications/Xcode.app/Contents/Developer/Platforms/iPhone* '
    sudo rm -r /Applications/Xcode.app/Contents/Developer/Platforms/iPhone* && echo "  - Done"
    du -hd 0 /Applications/Xcode.app/Contents/Developer/
    echo "Delete XCode Device Platforms - Done"
fi
