#!/usr/bin/env python3
import random
import sys
from faker import Faker
fake = Faker(['it_IT', 'en_US', 'ja_JP', 'ar_EG', 'zh_CN', 'ru_RU'])
extensions = ['dat', 'img', 'jpg', 'txt', 'doc', 'db']

def get_fake_filename():
    name = fake.name()
    if random.randint(0, 3) > 2:
        name = name.replace(' ', '_')
    if random.randint(0, 3) > 2:
        name = name.lower()
    idx = random.randint(0xff, 0xffffff)
    return f'{name}.{idx}.{random.choice(extensions)}'




count = int(sys.argv[1] if len(sys.argv) > 1 else 10)
for i in range(0, count):
    filename = get_fake_filename()
    print(f'{i} - {filename}')

