#!/usr/bin/env bash
title() {
    echo "------------------------------------------------------------"
    echo "${@}"
}
cd "$(dirname "$(readlink -f "${0}")")"
echo "Working directory is ${PWD}"

title "Execute: backup chrome script"
../../../tools/chrome.sh backup

title "Execute: backup private-workspace script"
./private-workspace backup

title "Done"
