#!/usr/bin/env bash
# ############################################################################
## Compress directory to zip archive.
## Usage: {SCRIPT_NAME} <dir>
# ############################################################################
NOCOLOR=''; RED=''; GREEN=''; YELLOW=''; BLUE=''; PURPLE=''; CYAN=''; WHITE=''; GRAY='';
# Settings for color output
# if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
if test -t 1 && [ "${NOCOLOR}" != "true" ] && [ "${NO_COLOR}" != "true" ]; then
    # see if it supports colors...
    ncolors=$(tput colors 2>/dev/null)
    if test -n "$ncolors" && test $ncolors -ge 8; then
        NOCOLOR='\033[0m'; RED='\033[1;31m'; GREEN='\033[1;32m'; YELLOW='\033[1;33m'; BLUE='\033[1;34m';
        PURPLE='\033[1;35m'; CYAN='\033[1;36m'; WHITE='\033[1;37m'; GRAY='\033[0;90m';
    fi
fi

debug() { echo >&2 -e "${CYAN}$*${NOCOLOR}"; }
info() { echo >&2 -e "${GREEN}$*${NOCOLOR}"; }
error() { echo >&2 -e "${RED}$*${NOCOLOR}"; exit 1; }

HASH_FILE=hash.md5
show_help() {
    sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0" | sed 's/{SCRIPT_NAME}/'"${0##*/}"'/g'
    exit 1
}

_dir_hash() {
    cd "${1}"
    rm -rf ./${HASH_FILE}
    debug "Calculating hashes for ${PWD}..."
    find . -type f | sort | while read fn; do md5sum "${fn}" | tee -a ./${HASH_FILE}; done
    printf "Hash file: "
    ls ./${HASH_FILE}
    cd - >/dev/null
    info "Calculated hashes for ${PWD} successfully"
}

_backup_directory() {
    dir_path="${1}"
    if [ -z "${dir_path}" ]; then error "Error: directory path is required"; fi
    tmpdir="/tmp/backup-dir-$(date +%Y%m%d%H%M%S)"
    _dir_hash "${dir_path}" || return 1
    # cat "${dir_path}/${HASH_FILE}" | md5sum
    dir_hash="$(cat "${dir_path}/${HASH_FILE}" | md5sum | cut -d" " -f1 | sed "s/ //g")"
    info "Hash: ${dir_path}=${dir_hash}"
    dir_name="$(basename "${dir_path}")"
    bak_file="${dir_name}.${dir_hash}.zip"
    debug "Backup ${dir_path} to ${bak_file}..."
    zip -vr "${bak_file}" "${dir_path}" || error "Error create archive"
    info "Backup ${dir_path} was created successfully"
    debug "Testing archive: extract into ${tmpdir}..."
    mkdir -p "${tmpdir}"
    unzip "${bak_file}" -d "${tmpdir}"
    cd "${tmpdir}/${dir_name}"
    debug "Check hash..."
    md5sum -c ./${HASH_FILE} || error "Error calculte hash"
    info "Tests are passed for ${bak_file}"
    cd - >/dev/null
    debug "Cleanup ${tmpdir}..."
    rm -rf "${tmpdir}"
    size="$(du -sh ${bak_file} | awk '{print $1}')"
    info "Backup file have been creted successfully: ${bak_file} (${size})"
}

src="${1:-"--help"}"
target_dir=
case "${src}" in
    help|--help|-h) show_help; exit 1;;
esac

if ! which zip >/dev/null; then
    echo "Error: zip is required."
    exit 1
fi

if ! which md5sum >/dev/null; then
    echo "Error: md5sum is required."
    exit 1
fi

_backup_directory "${src}"
