#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import sys

conversion = {
    "А": "A",
    "Б": "B",
    "В": "V",
    "Г": "G",
    "Д": "D",
    "Е": "E",
    "Ё": "E",
    "Ж": "Zh",
    "З": "Z",
    "И": "I",
    "Й": "Y",
    "К": "K",
    "Л": "L",
    "М": "M",
    "Н": "N",
    "О": "O",
    "П": "P",
    "Р": "R",
    "С": "S",
    "Т": "T",
    "У": "U",
    "Ф": "F",
    "Х": "H",
    "Ц": "Ts",
    "Ч": "Ch",
    "Ш": "Sh",
    "Щ": "Sch",
    "Ъ": "",
    "Ы": "Y",
    "Ь": "",
    "Э": "E",
    "Ю": "J",
    "Я": "Ja",
    "а": "a",
    "б": "b",
    "в": "v",
    "г": "g",
    "д": "d",
    "е": "e",
    "ё": "e",
    "ж": "zh",
    "з": "z",
    "и": "i",
    "й": "y",
    "к": "k",
    "л": "l",
    "м": "m",
    "н": "n",
    "о": "o",
    "п": "p",
    "р": "r",
    "с": "s",
    "т": "t",
    "у": "",
    "ф": "f",
    "х": "h",
    "ц": "ts",
    "ч": "ch",
    "ш": "sh",
    "щ": "sch",
    "ъ": "",
    "ы": "y",
    "ь": "",
    "э": "e",
    "ю": "j",
    "я": "ja",
}


def cyr2lat(text):
    result = []
    for ch in text:
        if ord(ch) > 128 and ch in conversion:
            ch = conversion[ch]
        # elif ch == ' ":
        #    ch = '-'
        result.append(ch)
    return ''.join(result)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        arg1 = sys.argv[1]
        if arg1 in ("--help", "-h", "help"):
            app = os.path.basename(__file__)
            print(f"Use: echo \"Пример текста\" | {app}")
        else:
            print(cyr2lat(arg1))
    else:
        for line in sys.stdin:
            sys.stdout.write(cyr2lat(line))

