#!/bin/sh
SCREENSHOT_LOCATION="${HOME}/Desktop/Screenshots"
ARCHIVE_LOCATION="${SCREENSHOT_LOCATION}/Archive"

backup_screenshots() {
    mkdir -p "${ARCHIVE_LOCATION}"
    target="${ARCHIVE_LOCATION}/$(date +"%Y-%m")/$(date +"%Y-%m-%d")"
    mkdir -p "${target}"
    echo "Backup old screenshots to the '${ARCHIVE_LOCATION}' directory..."
    find "${SCREENSHOT_LOCATION}" -type f -mtime +1 | while read f; do
        name=$(basename "${f}")
        # date=$(echo "${name}" | cut -d" " -f2)
        # target="${ARCHIVE_LOCATION}/${date:0:7}/${date}"
        # mkdir -p "${target}"
        mv -v "${f}" "${target}/${name}"
    done
    echo "Done"
}

cmd="${1:-open}"
case "${cmd}" in
    backup|bak) backup_screenshots ;;
    open) open "${SCREENSHOT_LOCATION}" ;;
    *) echo "Error: unknown command '${cmd}'"; exit 1;;
esac
