#!/usr/bin/env bash
# shellcheck shell=sh disable=SC3014 source=/dev/null
# ############################################################################
## Utility script to use a Telegram Bot
##
## Usage: {SCRIPT_NAME} [--alert] [--warning] [--debug] [message]
# ############################################################################
debug() { [ "${DEBUG:-""}" == "true" ] && >&2 echo "$*"; }
show_help() {
    sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0" | sed 's/{SCRIPT_NAME}/'"${0##*/}"'/g'
    exit 1
}

api_token=${TELEGRAM_TOKEN:-""}
chat_id=${TELEGRAM_CHAT_ID:-""}

send_message() {
    flag="${1}"
    message="${2:-""}"
    if [ -z "${message}" ]; then
        debug "Read message form the stdin:"
        message=$(cat /dev/stdin)
    fi
    url="https://api.telegram.org/bot${api_token}/sendMessage"
    debug "Sending message..."
    debug "Source message: ${message}"
    message="$(echo -n "${flag} ${message}" | tr '\n' '▐' | sed 's/▐/%0A/g')"
    debug "Message: ${message}" 
    url="${url}?chat_id=${chat_id}&text=${message}"
    debug "url=${url}"
    output="$(mktemp).log"
    if command -v  curl >/dev/null; then curl -sL "${url}" > "${output}";
    else  wget -qO - "${url}" > "${output}"; fi
    # TODO: add error check
    debug "Sending message success"
    echo "----------------------------------------"
    cat "${output}"
    echo "----------------------------------------"
    echo ""
    rm -f "${output}"
}

flag=✉️
message=""
for arg in "$@"; do
    case "${arg:-""}" in
        help|--help|-h) show_help; exit 1;;
        --alert) flag=❗;;
        --warning) flag=⚠️;;
        --debug) DEBUG=true;;
        *) message="${arg}"
    esac
done

send_message "${flag}" "${message}"