#!/bin/sh

show_help() {
    [ -n "$1" ] && echo "Error: unknown command '$1'."
    echo "Help"
    exit 255
}

show_prj_info() {
    echo "-------------------------------------------------------------"
    echo "Project name: ${NAME}"
    echo "Virtual env : ${VENV}"
    echo "-------------------------------------------------------------"
}

confirm() {
    echo $1
    opt=
    read -n 1 -p "$2 " opt
    echo ""
    if [ "${opt}" == "y" ] || [ "${opt}" == "Y" ]; then
        return 0
    fi
    return 1
}

NAME=$(basename "${PWD}")
VENV=${PYTHON_VIRTUAL_ENV:-"${HOME}/.cache/python/venv"}/${NAME}

case "${1}" in
    info)
        show_prj_info
        if [ -d "${VENV}" ]; then
            "${VENV}/bin/python" --version
            "${VENV}/bin/pip" --version
            "${VENV}/bin/pip" freeze
        else
            echo "Error: directory '${VENV}' not found."
            exit 1
        fi
        ;;
    init|start)
        show_prj_info
        if [ -d "${VENV}" ]; then
            if confirm "Directory '${VENV}' exists." "Do you want to override it (y/N)?"; then
                rm -rf "${VENV}"
            else
                echo "Skip"; exit 1
            fi
        fi
        echo "Creating virtual environment inside '${VENV}'..."
        python3 -m venv "${VENV}" && printf "Done: " && "${VENV}/bin/python" --version && \
        echo "Use 'source $(basename "${0}") activate' command to activate new virtual environment."
        ;;
    activate)
        if [ -d "${VENV}" ]; then
            source "${VENV}/bin/activate"
        else
            echo "Error: directory '${VENV}' not found. Please initialize virtual environment first."
            exit 1
        fi
        ;;
    clean|remove)
        show_prj_info
        "${VENV}/bin/deactivate" 2>/dev/null
        if [ -d "${VENV}" ]; then
            echo "Removing virtual environment '${VENV}'..."
            rm -rf "${VENV}" && echo "Done"
        else
            echo "Directory '${VENV}' not found."
        fi
        ;;
    *) show_help "$1"
esac        

