name: User-Environment-Tests

on:
  # schedule:
  #   - cron: "15 * * * *"
  #   - cron: "45 * * * *"
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  tests-on-ubuntu:
    runs-on: ubuntu-latest
    name: "Validate repository"
    env:
      REPO_BRANCH: develop
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Run syntax check
        id: lints
        run: |
          env | sort
          ./tools/shlint ./home/.local/bin/ && \
          ./tools/shlint ./tools/
      - name: Run tests
        id: tests
        run: |
          ./install.sh --noninteractive && bash -i ./tests/run-all-tests.sh
      - name: Notification
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DEBUG: true
          TESTS_RESULT:
        run: |
          echo "${{ toJson(steps.lints) }}"
          echo "${{ toJson(steps.tests) }}"
          action_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          flag=
          if [ "${{steps.lints.outcome}}" != "success" ] || [ "${{steps.tests.outcome}}" != "success" ]; then
            flag='--warning'
          fi
          (echo "Github '${GITHUB_WORKFLOW}' result:"
           echo "repo=${GITHUB_REPOSITORY},"
           echo "event=${GITHUB_EVENT_NAME},"
           echo "status-linter=${{steps.lints.outcome}},"
           echo "status-tests=${{steps.tests.outcome}},"
           echo "action=${action_url},"
           echo "time=$(date -u +"%FT%T%Z")") | ./tools/telebot "${flag}"
