name: MYENV - Tests

on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  tests-on-ubuntu:
    runs-on: ubuntu-latest
    name: "Execute tests on Ubuntu"
    env:
      REPO_BRANCH: develop
    with:
      ref: develop
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Run tests
        id: tests
        run: |
          ./install.sh --noninteractive && ./tests/test-installation.sh
      - name: Notification
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DEBUG: true
          TESTS_RESULT: ${{ toJson(steps.tests) }}
        run: |
          echo "${TESTS_RESULT}"
          ./tools/telebot send "Github action result: ${{ steps.tests.outcome }}"
